# Generated by Django 5.2.8 on 2026-03-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0006_alter_equipoentrenador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('tipo', models.CharField(choices=[('fuerza', 'Fuerza'), ('tactico', 'Táctico'), ('ataque', 'Ataque'), ('defensa', 'Defensa'), ('recuperacion', 'Recuperación')], max_length=20, verbose_name='Tipo de entrenamiento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['equipo', 'fecha_hora'], name='eventos_ent_equipo__23582f_idx'), models.Index(fields=['fecha_hora'], name='eventos_ent_fecha_h_6fcec9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo_visitante', models.CharField(blank=True, max_length=100, verbose_name='Nombre equipo visitante (manual)')),
                ('estadio_nombre', models.CharField(max_length=150, verbose_name='Nombre del estadio')),
                ('estadio_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección del estadio')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('posesion_local', models.IntegerField(default=0, help_text='Porcentaje de posesión del equipo local', verbose_name='Posesión local (%)')),
                ('posesion_visitante', models.IntegerField(default=0, help_text='Porcentaje de posesión del equipo visitante', verbose_name='Posesión visitante (%)')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Partido finalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='equipos.equipo', verbose_name='Equipo local')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_visitante', to='equipos.equipo', verbose_name='Equipo visitante (BD)')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['equipo_local', 'fecha_hora'], name='eventos_par_equipo__5f4f5d_idx'), models.Index(fields=['fecha_hora'], name='eventos_par_fecha_h_fe4760_idx')],
            },
        ),
    ]
