# Generated by Django 5.2.8 on 2026-04-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Liga Local 2024-2025', max_length=200, verbose_name='Nombre de la competición')),
                ('ano', models.PositiveIntegerField(help_text='Año de inicio de la temporada', verbose_name='Año/Temporada')),
                ('tipo', models.CharField(choices=[('liga', 'Liga'), ('copa', 'Copa'), ('amistoso', 'Amistoso'), ('torneo', 'Torneo'), ('supercopa', 'Supercopa')], default='liga', max_length=15, verbose_name='Tipo de competición')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('activa', models.BooleanField(default=True, verbose_name='Competición activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Competición',
                'verbose_name_plural': 'Competiciones',
                'ordering': ['-ano', 'nombre'],
                'indexes': [models.Index(fields=['ano', 'tipo'], name='eventos_com_ano_5f5a50_idx')],
                'unique_together': {('nombre', 'ano', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='competicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='eventos.competicion', verbose_name='Competición'),
        ),
    ]
