# Generated by Django 5.2.6 on 2026-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_competicion_partido_competicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles equipo local'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Goles equipo visitante'),
        ),
    ]
