# Generated by Django 5.2.6 on 2026-05-17 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0003_partido_goles_local_partido_goles_visitante'),
        ('usuarios', '0005_perfiljugador_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField(default=False, verbose_name='¿Fue titular?')),
                ('minutos_jugados', models.PositiveIntegerField(default=0, help_text='Minutos que jugó en el partido', verbose_name='Minutos jugados')),
                ('goles', models.PositiveIntegerField(default=0, verbose_name='Goles')),
                ('asistencias', models.PositiveIntegerField(default=0, verbose_name='Asistencias')),
                ('tiros', models.PositiveIntegerField(default=0, help_text='Tiros que fueron a puerta', verbose_name='Tiros a puerta')),
                ('pases', models.PositiveIntegerField(default=0, verbose_name='Pases completados')),
                ('fueras_de_juego', models.PositiveIntegerField(default=0, verbose_name='Fueras de juego')),
                ('paradas', models.PositiveIntegerField(default=0, help_text='Solo para porteros', verbose_name='Paradas')),
                ('despejes', models.PositiveIntegerField(default=0, verbose_name='Despejes')),
                ('faltas', models.PositiveIntegerField(default=0, verbose_name='Faltas cometidas')),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Tarjetas amarillas')),
                ('tarjeta_roja', models.BooleanField(default=False, verbose_name='¿Recibió tarjeta roja?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='usuarios.perfiljugador', verbose_name='Jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='eventos.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partido', 'jugador'], name='estadistica_partido_8c56aa_idx'), models.Index(fields=['jugador', '-created_at'], name='estadistica_jugador_7add05_idx')],
                'constraints': [models.UniqueConstraint(fields=('partido', 'jugador'), name='estadistica_unica_por_jugador_partido')],
                'unique_together': {('partido', 'jugador')},
            },
        ),
    ]
