# Generated by Django 5.2.8 on 2026-04-21 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_perfiljugador_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('muscular', 'Lesión muscular'), ('fractura', 'Fractura'), ('distension', 'Distensión'), ('contusion', 'Contusión'), ('esguince', 'Esguince'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo de lesión')),
                ('dias_duracion', models.PositiveIntegerField(verbose_name='Duración estimada (días)')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de lesión')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Lesión activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones', to='usuarios.perfiljugador', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Lesión',
                'verbose_name_plural': 'Lesiones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amarilla', 'Tarjeta amarilla'), ('roja', 'Tarjeta roja'), ('suspension', 'Suspensión'), ('amonestacion', 'Amonestación')], max_length=20, verbose_name='Tipo de sanción')),
                ('partidos_duracion', models.PositiveIntegerField(default=0, verbose_name='Partidos de suspensión')),
                ('razon', models.TextField(verbose_name='Razón de la sanción')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de sanción')),
                ('activa', models.BooleanField(default=True, verbose_name='Sanción activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='usuarios.perfiljugador', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
