# Generated by Django 5.2.8 on 2026-04-23 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_jugadores', '0001_initial'),
        ('usuarios', '0005_perfiljugador_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amarilla', 'Tarjeta amarilla'), ('roja', 'Tarjeta roja'), ('suspension', 'Suspensión'), ('amonestacion', 'Amonestación'), ('acumulacion', 'Acumulación de tarjetas')], max_length=20, verbose_name='Tipo de aviso')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto del aviso')),
                ('mensaje', models.TextField(verbose_name='Mensaje del aviso')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('enviado_email', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='usuarios.perfiljugador', verbose_name='Jugador')),
                ('sancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='control_jugadores.sancion', verbose_name='Sanción asociada')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
