# Generated by Django 5.2.8 on 2026-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_jugadores', '0002_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se detectó la lectura del email', null=True, verbose_name='Fecha de lectura'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='token_pixel',
            field=models.CharField(blank=True, help_text='Token único para detectar lectura de email', max_length=64, null=True, unique=True, verbose_name='Token para pixel tracking'),
        ),
    ]
