# Generated by Django 5.2.8 on 2026-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_jugadores', '0003_aviso_fecha_lectura_aviso_token_pixel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='fecha_lectura',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='token_pixel',
        ),
    ]
