# Generated by Django 5.2.8 on 2026-04-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_alter_equipoentrenador_options_and_more'),
        ('usuarios', '0005_perfiljugador_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='entrenador_interino',
            field=models.OneToOneField(blank=True, help_text='Entrenador interino cuando no hay entrenador principal activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_interino', to='usuarios.perfilentrenador', verbose_name='Entrenador interino'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='es_activo',
            field=models.BooleanField(default=True, help_text='Marca si el equipo está activo en el sistema', verbose_name='Equipo activo'),
        ),
        migrations.CreateModel(
            name='SolicitudEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado de la solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje del entrenador al solicitar', verbose_name='Mensaje adicional')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Explicación si se rechaza la solicitud', verbose_name='Motivo del rechazo')),
                ('entrenador_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_equipo', to='usuarios.perfilentrenador', verbose_name='Entrenador solicitante')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_entrenador', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Solicitud de Entrenador',
                'verbose_name_plural': 'Solicitudes de Entrenadores',
                'ordering': ['-fecha_solicitud'],
                'unique_together': {('equipo', 'entrenador_solicitante', 'estado')},
            },
        ),
    ]
