# Generated by Django 5.2.8 on 2026-05-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_equipo_entrenador_interino_equipo_es_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='entrenador_interino',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='es_activo',
        ),
        migrations.DeleteModel(
            name='SolicitudEntrenador',
        ),
    ]
